// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgent(arg1) {
  return window['go']['main']['App']['AddAgent'](arg1);
}

export function AddAgentRepo(arg1, arg2) {
  return window['go']['main']['App']['AddAgentRepo'](arg1, arg2);
}

export function CancelSession(arg1) {
  return window['go']['main']['App']['CancelSession'](arg1);
}

export function GetAgentPreamble() {
  return window['go']['main']['App']['GetAgentPreamble']();
}

export function GetCardSessions(arg1) {
  return window['go']['main']['App']['GetCardSessions'](arg1);
}

export function ListAgentRepos() {
  return window['go']['main']['App']['ListAgentRepos']();
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function RemoveAgent(arg1) {
  return window['go']['main']['App']['RemoveAgent'](arg1);
}

export function RemoveAgentRepo(arg1) {
  return window['go']['main']['App']['RemoveAgentRepo'](arg1);
}

export function SetAgentPreamble(arg1) {
  return window['go']['main']['App']['SetAgentPreamble'](arg1);
}

export function UpdateAgent(arg1) {
  return window['go']['main']['App']['UpdateAgent'](arg1);
}
