// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgentRepo(arg1:string,arg2:string):Promise<string>;

export function CancelSession(arg1:string):Promise<boolean>;

export function GetCardSessions(arg1:string):Promise<string>;

export function ListAgentRepos():Promise<string>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function PickDirectory(arg1:string):Promise<string>;

export function RemoveAgentRepo(arg1:string):Promise<void>;
