// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgentRepo(arg1, arg2) {
  return window['go']['main']['App']['AddAgentRepo'](arg1, arg2);
}

export function CancelSession(arg1) {
  return window['go']['main']['App']['CancelSession'](arg1);
}

export function GetCardSessions(arg1) {
  return window['go']['main']['App']['GetCardSessions'](arg1);
}

export function ListAgentRepos() {
  return window['go']['main']['App']['ListAgentRepos']();
}

export function OpenInBrowser(arg1) {
  return window['go']['main']['App']['OpenInBrowser'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['main']['App']['PickDirectory'](arg1);
}

export function RemoveAgentRepo(arg1) {
  return window['go']['main']['App']['RemoveAgentRepo'](arg1);
}
