package acp

import (
	"fmt"
	"strings"
)

// A flow is the route a card takes across the board: a graph of nodes (a column
// plus what runs when a card lands in it) and edges (which event moves the card
// on, and where). Several routes coexist — not every task is deployed — so a
// flow is a named registry entry a card is matched to, exactly like the repo,
// agent and deploy-target registries.
//
// The set of edge triggers is closed and implemented in Go (see FlowTriggers):
// the graph says *what* connects to what, the code decides *when*. Nothing in
// the config is interpreted as a script.

// Node actions: what runs when a card enters the node.
const (
	FlowActionNone   = "none"   // nothing runs; the card waits for an event
	FlowActionAgent  = "agent"  // an ordinary agent session on the card task
	FlowActionDeploy = "deploy" // a deploy session (Dokku)
	FlowActionTest   = "test"   // a browser test session against the preview
)

// Edge triggers. The outcome ones are produced by the node's own action; the
// rest come from the VCS watcher.
const (
	TriggerSuccess = "success"
	TriggerFailure = "failure"
	TriggerBlocked = "blocked"

	TriggerBranchPushed = "branch.pushed"
	TriggerBranchMerged = "branch.merged"

	TriggerPROpened       = "pr.opened"
	TriggerPRMerged       = "pr.merged"
	TriggerPRClosed       = "pr.closed"
	TriggerReviewApproved = "review.approved"
	TriggerChecksPassed   = "checks.passed"
	TriggerChecksFailed   = "checks.failed"
)

// Trigger sources, which decide who can produce an event and what the watcher
// has to poll for.
const (
	SourceOutcome = "outcome" // the node's own action finished
	SourceGit     = "git"     // local repository, no authentication
	SourceGitHub  = "github"  // GitHub API, needs a token for private repos
)

// FlowTrigger describes one edge trigger. The list doubles as the editor's
// dropdown, so the UI can never offer a trigger the engine does not implement.
type FlowTrigger struct {
	Kind   string `json:"kind"`
	Source string `json:"source"`
	Label  string `json:"label"`
}

// FlowTriggers is the closed set, in the order the editor shows them.
var FlowTriggers = []FlowTrigger{
	{Kind: TriggerSuccess, Source: SourceOutcome, Label: "шаг прошёл"},
	{Kind: TriggerFailure, Source: SourceOutcome, Label: "шаг упал"},
	{Kind: TriggerBlocked, Source: SourceOutcome, Label: "проверить не удалось"},
	{Kind: TriggerBranchPushed, Source: SourceGit, Label: "ветка запушена"},
	{Kind: TriggerBranchMerged, Source: SourceGit, Label: "ветка влита в основную"},
	{Kind: TriggerPROpened, Source: SourceGitHub, Label: "открыт pull request"},
	{Kind: TriggerPRMerged, Source: SourceGitHub, Label: "pull request смержен"},
	{Kind: TriggerPRClosed, Source: SourceGitHub, Label: "pull request закрыт"},
	{Kind: TriggerReviewApproved, Source: SourceGitHub, Label: "ревью одобрено"},
	{Kind: TriggerChecksPassed, Source: SourceGitHub, Label: "проверки прошли"},
	{Kind: TriggerChecksFailed, Source: SourceGitHub, Label: "проверки упали"},
}

// FlowEntry is one named route in the registry.
type FlowEntry struct {
	Name string `json:"name"` // registry key; matches the card "Flow" option

	// RepoName ties the flow to an entry of the repo registry, so a card that
	// only names its repository still finds its route.
	RepoName string `json:"repoName,omitempty"`
	// Property is the select property whose options are the flow's columns.
	// Empty means Config.TriggerProperty.
	Property string `json:"property,omitempty"`

	Nodes []FlowNode `json:"nodes"`
	Edges []FlowEdge `json:"edges"`
}

// FlowNode is one stage: a column of the board and what runs on entering it.
type FlowNode struct {
	ID     string `json:"id"`     // stable identifier, generated by the editor
	Column string `json:"column"` // option name on the board
	Action string `json:"action"` // FlowAction*

	// AgentName and DeployName override the registries for this node only.
	AgentName  string `json:"agentName,omitempty"`
	DeployName string `json:"deployName,omitempty"`
}

// FlowEdge is one transition. On is a FlowTrigger kind; success/failure are the
// node's own outcomes, which the editor shows as the node's two outputs.
type FlowEdge struct {
	From string `json:"from"`
	To   string `json:"to"`
	On   string `json:"on"`
}

// Trigger looks a trigger kind up in the closed set.
func Trigger(kind string) (FlowTrigger, bool) {
	for _, t := range FlowTriggers {
		if t.Kind == kind {
			return t, true
		}
	}
	return FlowTrigger{}, false
}

// TriggerLabel is the human phrasing used in card comments.
func TriggerLabel(kind string) string {
	if t, ok := Trigger(kind); ok {
		return t.Label
	}
	return kind
}

// IsVCSTrigger reports whether the trigger comes from the repository rather
// than from the node's own action — the ones the watcher has to poll for.
func IsVCSTrigger(kind string) bool {
	t, ok := Trigger(kind)
	return ok && t.Source != SourceOutcome
}

// IsGitHubTrigger reports whether the trigger needs the GitHub API.
func IsGitHubTrigger(kind string) bool {
	t, ok := Trigger(kind)
	return ok && t.Source == SourceGitHub
}

// Node returns the node with the given id.
func (f FlowEntry) Node(id string) (FlowNode, bool) {
	for _, n := range f.Nodes {
		if n.ID == id {
			return n, true
		}
	}
	return FlowNode{}, false
}

// NodeByColumn returns the node sitting on a column, matched the way every
// other column comparison in the package is: case-insensitively.
func (f FlowEntry) NodeByColumn(column string) (FlowNode, bool) {
	column = strings.TrimSpace(column)
	if column == "" {
		return FlowNode{}, false
	}
	for _, n := range f.Nodes {
		if strings.EqualFold(n.Column, column) {
			return n, true
		}
	}
	return FlowNode{}, false
}

// Next returns the node an event moves the card to.
func (f FlowEntry) Next(nodeID, on string) (FlowNode, bool) {
	for _, e := range f.Edges {
		if e.From == nodeID && e.On == on {
			return f.Node(e.To)
		}
	}
	return FlowNode{}, false
}

// WaitsFor lists the VCS triggers a node has edges for. An empty result means
// the card parked on this node needs no polling at all.
func (f FlowEntry) WaitsFor(nodeID string) []string {
	var out []string
	for _, e := range f.Edges {
		if e.From == nodeID && IsVCSTrigger(e.On) {
			out = append(out, e.On)
		}
	}
	return out
}

// PropertyOr returns the select property the flow's columns belong to.
func (f FlowEntry) PropertyOr(fallback string) string {
	if p := strings.TrimSpace(f.Property); p != "" {
		return p
	}
	return fallback
}

// Flows returns a snapshot of the registry.
func (m *Manager) Flows() []FlowEntry {
	m.cfgMu.RLock()
	defer m.cfgMu.RUnlock()
	return append([]FlowEntry(nil), m.cfg.Flows...)
}

// validateFlow normalizes and checks one route. repos/agents/deploys are the
// registries its nodes may reference.
func validateFlow(f FlowEntry, repos []RepoEntry, agents []AgentEntry, deploys []DeployEntry) (FlowEntry, error) {
	f.Name = strings.TrimSpace(f.Name)
	if f.Name == "" {
		return FlowEntry{}, fmt.Errorf("имя флоу не может быть пустым")
	}
	f.RepoName = strings.TrimSpace(f.RepoName)
	if f.RepoName != "" && !hasRepo(repos, f.RepoName) {
		return FlowEntry{}, fmt.Errorf("репозиторий %q не найден в реестре (%s)", f.RepoName, repoNames(repos))
	}
	f.Property = strings.TrimSpace(f.Property)
	if len(f.Nodes) == 0 {
		return FlowEntry{}, fmt.Errorf("флоу %q не содержит ни одной стадии", f.Name)
	}

	seenID := make(map[string]bool, len(f.Nodes))
	seenColumn := make(map[string]bool, len(f.Nodes))
	for i, n := range f.Nodes {
		n.ID = strings.TrimSpace(n.ID)
		n.Column = strings.TrimSpace(n.Column)
		n.Action = strings.TrimSpace(n.Action)
		if n.Action == "" {
			n.Action = FlowActionNone
		}
		if n.ID == "" {
			return FlowEntry{}, fmt.Errorf("у стадии %d нет идентификатора", i+1)
		}
		if seenID[n.ID] {
			return FlowEntry{}, fmt.Errorf("идентификатор стадии %q встречается дважды", n.ID)
		}
		if n.Column == "" {
			return FlowEntry{}, fmt.Errorf("у стадии %q не выбрана колонка", n.ID)
		}
		lower := strings.ToLower(n.Column)
		if seenColumn[lower] {
			return FlowEntry{}, fmt.Errorf("колонка %q занята двумя стадиями — карточка не сможет понять, где она", n.Column)
		}
		switch n.Action {
		case FlowActionNone, FlowActionAgent, FlowActionDeploy, FlowActionTest:
		default:
			return FlowEntry{}, fmt.Errorf("неизвестное действие %q у стадии %q", n.Action, n.ID)
		}
		n.AgentName = strings.TrimSpace(n.AgentName)
		if n.AgentName != "" && !hasAgent(agents, n.AgentName) {
			return FlowEntry{}, fmt.Errorf("агент %q стадии %q не найден в реестре (%s)", n.AgentName, n.ID, agentNames(agents))
		}
		n.DeployName = strings.TrimSpace(n.DeployName)
		if n.DeployName != "" && !hasDeploy(deploys, n.DeployName) {
			return FlowEntry{}, fmt.Errorf("цель деплоя %q стадии %q не найдена в реестре (%s)", n.DeployName, n.ID, deployNames(deploys))
		}
		seenID[n.ID] = true
		seenColumn[lower] = true
		f.Nodes[i] = n
	}

	seenEdge := make(map[string]bool, len(f.Edges))
	for i, e := range f.Edges {
		e.From = strings.TrimSpace(e.From)
		e.To = strings.TrimSpace(e.To)
		e.On = strings.TrimSpace(e.On)
		if !seenID[e.From] {
			return FlowEntry{}, fmt.Errorf("переход ведёт из несуществующей стадии %q", e.From)
		}
		if !seenID[e.To] {
			return FlowEntry{}, fmt.Errorf("переход из %q ведёт в несуществующую стадию %q", e.From, e.To)
		}
		if _, ok := Trigger(e.On); !ok {
			return FlowEntry{}, fmt.Errorf("неизвестное событие перехода %q", e.On)
		}
		key := e.From + "|" + e.On
		if seenEdge[key] {
			return FlowEntry{}, fmt.Errorf("у стадии %q два перехода по событию %q — куда ехать, непонятно", e.From, TriggerLabel(e.On))
		}
		seenEdge[key] = true
		f.Edges[i] = e
	}
	return f, nil
}

// AddFlow registers a new route and persists the config.
func (m *Manager) AddFlow(f FlowEntry) (FlowEntry, error) {
	m.cfgMu.Lock()
	defer m.cfgMu.Unlock()
	f, err := validateFlow(f, m.cfg.Repos, m.cfg.Agents, m.cfg.Deploys)
	if err != nil {
		return FlowEntry{}, err
	}
	for _, e := range m.cfg.Flows {
		if strings.EqualFold(e.Name, f.Name) {
			return FlowEntry{}, fmt.Errorf("флоу с именем %q уже существует", e.Name)
		}
	}
	m.cfg.Flows = append(m.cfg.Flows, f)
	return f, m.persistConfigLocked()
}

// UpdateFlow replaces an existing route (matched by name) and persists.
func (m *Manager) UpdateFlow(f FlowEntry) (FlowEntry, error) {
	m.cfgMu.Lock()
	defer m.cfgMu.Unlock()
	f, err := validateFlow(f, m.cfg.Repos, m.cfg.Agents, m.cfg.Deploys)
	if err != nil {
		return FlowEntry{}, err
	}
	for i, e := range m.cfg.Flows {
		if strings.EqualFold(e.Name, f.Name) {
			m.cfg.Flows[i] = f
			return f, m.persistConfigLocked()
		}
	}
	return FlowEntry{}, fmt.Errorf("флоу %q не найден", f.Name)
}

// RemoveFlow deletes a route by name and persists. Cards currently on it stop
// moving by themselves; nothing else happens to them.
func (m *Manager) RemoveFlow(name string) error {
	m.cfgMu.Lock()
	defer m.cfgMu.Unlock()
	for i, e := range m.cfg.Flows {
		if strings.EqualFold(e.Name, name) {
			m.cfg.Flows = append(m.cfg.Flows[:i], m.cfg.Flows[i+1:]...)
			return m.persistConfigLocked()
		}
	}
	return fmt.Errorf("флоу %q не найден", name)
}

// resolveFlow maps a card to its route. Priority mirrors every other registry:
//  1. a "flow" property or a select option naming an entry;
//  2. the flow tied to the repository the card resolved to;
//  3. the single registered flow.
//
// Nothing matched is not an error: the card simply has no route, and the legacy
// trigger columns keep working for it.
func (m *Manager) resolveFlow(ev CardMoved, repoPath string) *FlowEntry {
	m.cfgMu.RLock()
	flows := append([]FlowEntry(nil), m.cfg.Flows...)
	repos := append([]RepoEntry(nil), m.cfg.Repos...)
	m.cfgMu.RUnlock()

	if len(flows) == 0 {
		return nil
	}
	find := func(name string) *FlowEntry {
		for i := range flows {
			if strings.EqualFold(strings.TrimSpace(name), flows[i].Name) {
				return &flows[i]
			}
		}
		return nil
	}
	if explicit := strings.TrimSpace(ev.Props["flow"]); explicit != "" {
		if f := find(explicit); f != nil {
			return f
		}
	}
	for _, opt := range ev.OptionNames {
		if f := find(opt); f != nil {
			return f
		}
	}
	if repoName := repoNameForPath(repos, repoPath); repoName != "" {
		for i := range flows {
			if strings.EqualFold(flows[i].RepoName, repoName) {
				return &flows[i]
			}
		}
	}
	if len(flows) == 1 {
		return &flows[0]
	}
	return nil
}

// FlowByName returns a registered route.
func (m *Manager) FlowByName(name string) (FlowEntry, bool) {
	m.cfgMu.RLock()
	defer m.cfgMu.RUnlock()
	for _, f := range m.cfg.Flows {
		if strings.EqualFold(f.Name, name) {
			return f, true
		}
	}
	return FlowEntry{}, false
}

func hasRepo(repos []RepoEntry, name string) bool {
	for _, r := range repos {
		if strings.EqualFold(r.Name, name) {
			return true
		}
	}
	return false
}

func hasAgent(agents []AgentEntry, name string) bool {
	for _, a := range agents {
		if strings.EqualFold(a.Name, name) {
			return true
		}
	}
	return false
}

func hasDeploy(deploys []DeployEntry, name string) bool {
	for _, d := range deploys {
		if strings.EqualFold(d.Name, name) {
			return true
		}
	}
	return false
}
