// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAgent(arg1:string):Promise<string>;

export function AddAgentRepo(arg1:string,arg2:string):Promise<string>;

export function AddProxy(arg1:string):Promise<string>;

export function CancelSession(arg1:string):Promise<boolean>;

export function GetAgentSystemPrompt():Promise<string>;

export function GetCardSessions(arg1:string):Promise<string>;

export function ListAgentRepos():Promise<string>;

export function ListAgents():Promise<string>;

export function ListProxies():Promise<string>;

export function OpenInBrowser(arg1:string):Promise<void>;

export function PickDirectory(arg1:string):Promise<string>;

export function RemoveAgent(arg1:string):Promise<void>;

export function RemoveAgentRepo(arg1:string):Promise<void>;

export function RemoveProxy(arg1:string):Promise<void>;

export function SetAgentSystemPrompt(arg1:string):Promise<void>;

export function UpdateAgent(arg1:string):Promise<string>;

export function UpdateProxy(arg1:string):Promise<string>;
